In [1]:
import pandas as pd

In [5]:
abc = pd.Series([4,5,7,2,8,3,9])

In [6]:
abc

0    4
1    5
2    7
3    2
4    8
5    3
6    9
dtype: int64

In [7]:
s = pd.Series([74,23,54,72,84,98,65], index=["harry","abhi","Ashi","aariv","ashwani","pawan","ganesh"])
s

harry      74
abhi       23
Ashi       54
aariv      72
ashwani    84
pawan      98
ganesh     65
dtype: int64

In [11]:
s[ "abhi"]

np.int64(23)

In [13]:
data = pd.read_csv("data.csv")

In [14]:
df = pd.DataFrame(data)

In [15]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [16]:
df.head(5)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

In [17]:
df.tail(5)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [18]:
df.columns

Index(['Actor', 'Film', 'Year', 'Genre', 'BoxOffice(INR Crore)', 'IMDb'], dtype='object')

In [19]:
df.loc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [20]:
df.iloc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

###creating dataframe

In [21]:
import pandas as pd

# List of lists
data = [
    [1, "Abhishek", 25],
    [2, "Rahul", 27],
    [3, "Ankit", 26]
]

df1 = pd.DataFrame(data, columns=["ID", "Name", "Age"])

print("DataFrame from List:")
print(df1)

DataFrame from List:
   ID      Name  Age
0   1  Abhishek   25
1   2     Rahul   27
2   3     Ankit   26

In [22]:
import pandas as pd

data = {
    "ID": [1,2,3],
    "Name": ["Abhishek","Rahul","Ankit"],
    "Age": [25,27,26]
}

df2 = pd.DataFrame(data)

print("\nDataFrame from Dictionary:")
print(df2)

DataFrame from Dictionary:
   ID      Name  Age
0   1  Abhishek   25
1   2     Rahul   27
2   3     Ankit   26

In [23]:
import pandas as pd

s1 = pd.Series([1,2,3])
s2 = pd.Series(["Abhishek","Rahul","Ankit"])
s3 = pd.Series([25,27,26])

df3 = pd.DataFrame({
    "ID": s1,
    "Name": s2,
    "Age": s3
})

print("\nDataFrame from Series:")
print(df3)

DataFrame from Series:
   ID      Name  Age
0   1  Abhishek   25
1   2     Rahul   27
2   3     Ankit   26

In [24]:
import pandas as pd

data = [
    {"ID":1, "Name":"Abhishek", "Age":25},
    {"ID":2, "Name":"Rahul", "Age":27},
    {"ID":3, "Name":"Ankit", "Age":26}
]

df4 = pd.DataFrame(data)

print("\nDataFrame from List of Dictionary:")
print(df4)

DataFrame from List of Dictionary:
   ID      Name  Age
0   1  Abhishek   25
1   2     Rahul   27
2   3     Ankit   26

In [25]:
import pandas as pd

df5 = pd.DataFrame()

print("\nEmpty DataFrame:")
print(df5)

Empty DataFrame:
Empty DataFrame
Columns: []
Index: []

In [26]:
import pandas as pd

data = {
    "Name": ["Abhishek","Rahul","Ankit"],
    "Age": [25,27,26]
}

df6 = pd.DataFrame(data, index=["A","B","C"])

print("\nDataFrame with Custom Index:")
print(df6)

DataFrame with Custom Index:
       Name  Age
A  Abhishek   25
B     Rahul   27
C     Ankit   26

In [27]:
import pandas as pd
import numpy as np

data = np.array([
    [1,25],
    [2,27],
    [3,26]
])

df7 = pd.DataFrame(data, columns=["ID","Age"])

print("\nDataFrame from NumPy:")
print(df7)

DataFrame from NumPy:
   ID  Age
0   1   25
1   2   27
2   3   26

In [28]:
import pandas as pd

df8 = pd.DataFrame()

df8["ID"] = [1,2,3]
df8["Name"] = ["Abhishek","Rahul","Ankit"]
df8["Age"] = [25,27,26]

print("\nDataFrame Column Wise:")
print(df8)

DataFrame Column Wise:
   ID      Name  Age
0   1  Abhishek   25
1   2     Rahul   27
2   3     Ankit   26

In [29]:
import pandas as pd

df9 = pd.read_csv("data.csv")

print("\nDataFrame from CSV:")
print(df9.head())

DataFrame from CSV:
            Actor             Film  Year       Genre  BoxOffice(INR Crore)  \
0  Shah Rukh Khan          Pathaan  2023      Action                  1050
1     Salman Khan  Tiger Zinda Hai  2017      Action                   565
2      Aamir Khan           Dangal  2016   Biography                  2024
3   Ranbir Kapoor       Brahmastra  2022     Fantasy                   431
4   Ranveer Singh        Padmaavat  2018  Historical                   585

   IMDb
0   7.2
1   6.0
2   8.4
3   5.6
4   7.0

In [31]:
file = pd.read_csv('data_cleaning_sample.csv')

In [32]:
df = pd.DataFrame(file)

In [33]:
df.head()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019

###JSON DATA

In [34]:
import pandas as pd

df = pd.read_json("data.json")

print(df.head())
print(df.shape)

   id    name  age     city  salary  department  experience_years  \
0   1  User_1   48  Kolkata   61894          HR                 9
1   2  User_2   42  Kolkata   35714  Operations                 5
2   3  User_3   37     Pune   62293          HR                 7
3   4  User_4   45   Mumbai   89321  Operations                 8
4   5  User_5   28  Chennai  107768          HR                 2

   performance_score              email  active
0               1.48  user1@example.com    True
1               1.23  user2@example.com    True
2               3.96  user3@example.com    True
3               3.35  user4@example.com   False
4               1.50  user5@example.com    True
(350, 10)

In [35]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 350 non-null    int64
 1   name               350 non-null    object
 2   age                350 non-null    int64
 3   city               350 non-null    object
 4   salary             350 non-null    int64
 5   department         350 non-null    object
 6   experience_years   350 non-null    int64
 7   performance_score  350 non-null    float64
 8   email              350 non-null    object
 9   active             350 non-null    bool
dtypes: bool(1), float64(1), int64(4), object(4)
memory usage: 25.1+ KB

,id,age,salary,experience_years,performance_score
count,350.000000,350.000000,350.000000,350.000000,350.000000
mean,175.500000,34.802857,73033.000000,7.902857,3.095771
std,101.180532,8.788407,26134.590031,4.277179,1.181830
min,1.000000,20.000000,30775.000000,1.000000,1.010000
25%,88.250000,27.250000,50206.250000,4.000000,2.082500
50%,175.500000,35.000000,71280.000000,7.000000,3.175000
75%,262.750000,42.000000,94663.500000,12.000000,4.097500
max,350.000000,50.000000,119521.000000,15.000000,4.990000

In [36]:
df[df['salary']>50000]

,id,name,age,city,salary,department,experience_years,performance_score,email,active
0,1,User_1,48,Kolkata,61894,HR,9,1.48,user1@example.com,True
2,3,User_3,37,Pune,62293,HR,7,3.96,user3@example.com,True
3,4,User_4,45,Mumbai,89321,Operations,8,3.35,user4@example.com,False
4,5,User_5,28,Chennai,107768,HR,2,1.50,user5@example.com,True
6,7,User_7,41,Kolkata,80561,IT,1,2.56,user7@example.com,True
...,...,...,...,...,...,...,...,...,...,...
343,344,User_344,23,Delhi,64520,Finance,5,2.71,user344@example.com,False
345,346,User_346,37,Delhi,69050,HR,14,1.15,user346@example.com,False
346,347,User_347,50,Bangalore,66928,Operations,7,1.03,user347@example.com,False
348,349,User_349,48,Kolkata,114926,Operations,2,4.30,user349@example.com,True
349,350,User_350,21,Bangalore,73501,Operations,8,1.55,user350@example.com,False

In [41]:
# df[(df["city"]=="Delhi") & (df["age"]>30)['name','department']]
df[(df["city"]=="Delhi") & (df["age"]>30)][['name','department']]

         name  department
5      User_6  Operations
9     User_10  Operations
14    User_15          HR
18    User_19     Finance
25    User_26  Operations
40    User_41       Sales
46    User_47          IT
53    User_54          HR
78    User_79          HR
104  User_105          IT
129  User_130  Operations
143  User_144  Operations
167  User_168          HR
179  User_180     Finance
185  User_186     Finance
199  User_200          IT
200  User_201     Finance
213  User_214  Operations
239  User_240  Operations
243  User_244          HR
266  User_267          HR
278  User_279       Sales
282  User_283     Finance
291  User_292          IT
299  User_300          HR
305  User_306     Finance
330  User_331          IT
334  User_335  Operations
337  User_338  Operations
345  User_346          HR

In [42]:
df.loc[
    (df["city"]=="Delhi") & (df["age"]>30),
    ["name","department"]
]

         name  department
5      User_6  Operations
9     User_10  Operations
14    User_15          HR
18    User_19     Finance
25    User_26  Operations
40    User_41       Sales
46    User_47          IT
53    User_54          HR
78    User_79          HR
104  User_105          IT
129  User_130  Operations
143  User_144  Operations
167  User_168          HR
179  User_180     Finance
185  User_186     Finance
199  User_200          IT
200  User_201     Finance
213  User_214  Operations
239  User_240  Operations
243  User_244          HR
266  User_267          HR
278  User_279       Sales
282  User_283     Finance
291  User_292          IT
299  User_300          HR
305  User_306     Finance
330  User_331          IT
334  User_335  Operations
337  User_338  Operations
345  User_346          HR

In [45]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df1 = pd.read_csv(url)

In [46]:
df1.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [47]:
df1.shape

(244, 7)

In [48]:
df1.size

1708

In [49]:
df1.set_axis

<bound method DataFrame.set_axis of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [50]:
df1.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [53]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [56]:
df1.to_csv('restaurants.csv', index=False)

In [57]:
file_save = df1.to_csv('restaurants1.csv', index=True)

In [60]:
df1.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [65]:
df1['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [64]:
df1[['total_bill', 'tip', 'sex']]

     total_bill   tip     sex
0         16.99  1.01  Female
1         10.34  1.66    Male
2         21.01  3.50    Male
3         23.68  3.31    Male
4         24.59  3.61  Female
..          ...   ...     ...
239       29.03  5.92    Male
240       27.18  2.00  Female
241       22.67  2.00    Male
242       17.82  1.75    Male
243       18.78  3.00  Female

[244 rows x 3 columns]

In [66]:
df1.loc[4]

total_bill     24.59
tip             3.61
sex           Female
smoker            No
day              Sun
time          Dinner
size               4
Name: 4, dtype: object

In [67]:
df1.loc[8,"sex"]

'Male'

In [68]:
df1.iloc[8,5]

'Dinner'

In [69]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')